# Generated by Django 2.1.4 on 2018-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
